/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.BookingHistory;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author it solution
 */
public class bookinghistory extends javax.swing.JFrame {

 
    public bookinghistory() {
        initComponents();
        customizeTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        Bookings = new javax.swing.JLabel();
        txtMovieTitle = new javax.swing.JTextField();
        ScrollPane = new javax.swing.JScrollPane();
        tblBookingHistory = new javax.swing.JTable();
        Panel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setText("Search");
        Panel.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, -1));

        Bookings.setBackground(new java.awt.Color(102, 102, 102));
        Bookings.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        Bookings.setText("Bookings");
        Panel.add(Bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 23, -1, 27));
        Panel.add(txtMovieTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 217, -1));

        ScrollPane.setBackground(new java.awt.Color(204, 204, 204));
        ScrollPane.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ScrollPane.setOpaque(false);

        tblBookingHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Movie Title", "Date/Time", "SeatNum", "Status", "ShowTime"
            }
        ));
        tblBookingHistory.getTableHeader().setReorderingAllowed(false);
        ScrollPane.setViewportView(tblBookingHistory);

        Panel.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 690, 340));

        Panel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/background.jpeg"))); // NOI18N
        Panel2.setText("jLabel1");
        Panel.add(Panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-12, -5, 830, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bookinghistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bookinghistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bookinghistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bookinghistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookinghistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bookings;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Panel2;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTable tblBookingHistory;
    private javax.swing.JTextField txtMovieTitle;
    // End of variables declaration//GEN-END:variables

    public String getEnteredMovieTitle(){
        return txtMovieTitle.getText().trim();
    }
    
    public void addSearchButtonListener(ActionListener listener){
        btnSearch.addActionListener(listener);
    }
    
    public void populateBookingTable(List<BookingHistory> bookingHistory) {
    DefaultTableModel model = (DefaultTableModel) tblBookingHistory.getModel();
    model.setRowCount(0); // Clear previous data

    for (BookingHistory booking : bookingHistory) {
        Object[] rowData = {
            booking.getBookingId(),
            booking.getMovieTitle(),
            booking.getBookingDateTime(),
            booking.getSeatNum(),
            booking.getShowTime(),
            booking.getStatus()
        };
        model.addRow(rowData);
    }
}

    public void showMessage(String message){
        JOptionPane.showMessageDialog(this, message);
    }
    
    private void customizeTableModel() {
    String[] columnNames = {"ID", "Movie Title", "Date/Time", "SeatNum", "ShowTime","Status"};
    DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;  // Make table non-editable
        }
    };
    tblBookingHistory.setModel(model);
}

}
