/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */
public class CheckSeatAvailability extends javax.swing.JFrame {

    /**
     * Creates new form CheckSeatAvailability
     */
    public CheckSeatAvailability() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        movieTitle = new javax.swing.JLabel();
        titleComboBox = new javax.swing.JComboBox<>();
        showTitle = new javax.swing.JLabel();
        timeComboBox = new javax.swing.JComboBox<>();
        title = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        filterSeats = new javax.swing.JLabel();
        filterComboBox = new javax.swing.JComboBox<>();
        availableSeats = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        availableLabel = new javax.swing.JLabel();
        bookLabel = new javax.swing.JLabel();
        preLabel = new javax.swing.JLabel();
        available = new javax.swing.JLabel();
        booked = new javax.swing.JLabel();
        premium = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setPreferredSize(new java.awt.Dimension(500, 350));
        MainPanel.setLayout(new java.awt.BorderLayout());

        TopPanel.setPreferredSize(new java.awt.Dimension(600, 80));

        movieTitle.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        movieTitle.setText("Movie Title: ");

        titleComboBox.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        titleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        showTitle.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        showTitle.setText("ShowTime: ");

        timeComboBox.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        timeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        title.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        title.setText("Check Seat Availability");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(movieTitle))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(showTitle)))
                .addGap(18, 18, 18)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleComboBox, 0, 202, Short.MAX_VALUE)
                    .addComponent(timeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addGap(0, 263, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(253, 253, 253))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(movieTitle)
                    .addComponent(titleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showTitle)
                    .addComponent(timeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        MainPanel.add(TopPanel, java.awt.BorderLayout.PAGE_START);

        BottomPanel.setPreferredSize(new java.awt.Dimension(700, 80));

        filterSeats.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        filterSeats.setText("Filter Seats: ");

        filterComboBox.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Premium", " " }));

        availableSeats.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        availableSeats.setText("Available Seats: 60");

        jLabel6.setBackground(new java.awt.Color(51, 204, 0));

        availableLabel.setBackground(new java.awt.Color(51, 153, 0));
        availableLabel.setForeground(new java.awt.Color(255, 255, 255));
        availableLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        availableLabel.setOpaque(true);

        bookLabel.setBackground(new java.awt.Color(204, 0, 0));
        bookLabel.setForeground(new java.awt.Color(255, 255, 255));
        bookLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bookLabel.setOpaque(true);

        preLabel.setBackground(new java.awt.Color(0, 0, 0));
        preLabel.setForeground(new java.awt.Color(255, 255, 255));
        preLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        preLabel.setOpaque(true);

        available.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        available.setText("Available");

        booked.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        booked.setText("Booked");

        premium.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        premium.setText("Premium");

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BottomPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(filterSeats)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(availableSeats))
                    .addGroup(BottomPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(availableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(available)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(booked)
                        .addGap(36, 36, 36)
                        .addComponent(preLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(premium)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        BottomPanelLayout.setVerticalGroup(
            BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BottomPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(BottomPanelLayout.createSequentialGroup()
                        .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(premium)
                            .addComponent(bookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(booked)
                            .addComponent(availableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(available))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterSeats)
                    .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availableSeats))
                .addGap(23, 23, 23))
        );

        MainPanel.add(BottomPanel, java.awt.BorderLayout.PAGE_END);

        CenterPanel.setMinimumSize(new java.awt.Dimension(580, 360));
        CenterPanel.setPreferredSize(new java.awt.Dimension(700, 440));
        CenterPanel.setLayout(new java.awt.GridLayout(8, 10, 5, 5));

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Screen");
        CenterPanel.add(jLabel13);

        MainPanel.add(CenterPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckSeatAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckSeatAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckSeatAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckSeatAvailability.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckSeatAvailability().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JPanel CenterPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel available;
    private javax.swing.JLabel availableLabel;
    private javax.swing.JLabel availableSeats;
    private javax.swing.JLabel bookLabel;
    private javax.swing.JLabel booked;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JLabel filterSeats;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel movieTitle;
    private javax.swing.JLabel preLabel;
    private javax.swing.JLabel premium;
    private javax.swing.JLabel showTitle;
    private javax.swing.JComboBox<String> timeComboBox;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> titleComboBox;
    // End of variables declaration//GEN-END:variables
}
