/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author it solution
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        homeLogo = new javax.swing.JLabel();
        profileLogo = new javax.swing.JLabel();
        transactionLogo = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        transactionButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        historyLogo = new javax.swing.JLabel();
        movie1 = new javax.swing.JPanel();
        movie2 = new javax.swing.JPanel();
        movie3 = new javax.swing.JPanel();
        poster1 = new javax.swing.JLabel();
        movie4 = new javax.swing.JPanel();
        movie5 = new javax.swing.JPanel();
        movie6 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        searchlogoButton = new javax.swing.JButton();
        meButton = new javax.swing.JButton();
        Nowshowing = new javax.swing.JTextField();
        upcoming = new javax.swing.JTextField();
        scrollButton = new javax.swing.JButton();
        scrollButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sidePanel.setBackground(new java.awt.Color(0, 0, 51));
        sidePanel.setDoubleBuffered(false);
        sidePanel.setEnabled(false);
        sidePanel.setFocusable(false);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/Group 37071 (1).png"))); // NOI18N

        homeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/Frame 37266 (1).png"))); // NOI18N

        profileLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/Frame 37267 (1).png"))); // NOI18N
        profileLogo.setText("jLabel3");

        transactionLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/Frame 37268 (2).png"))); // NOI18N
        transactionLogo.setText("jLabel4");

        homeButton.setBackground(new java.awt.Color(0, 0, 51));
        homeButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        homeButton.setForeground(new java.awt.Color(242, 242, 242));
        homeButton.setText("Home");
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setDefaultCapable(false);
        homeButton.setEnabled(false);
        homeButton.setFocusPainted(false);
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(0, 0, 51));
        profileButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        profileButton.setForeground(new java.awt.Color(242, 242, 242));
        profileButton.setText("Profile");
        profileButton.setBorderPainted(false);
        profileButton.setContentAreaFilled(false);
        profileButton.setDefaultCapable(false);
        profileButton.setEnabled(false);
        profileButton.setFocusPainted(false);
        profileButton.setFocusable(false);
        profileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        transactionButton.setBackground(new java.awt.Color(0, 0, 51));
        transactionButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        transactionButton.setForeground(new java.awt.Color(242, 242, 242));
        transactionButton.setText("Transaction");
        transactionButton.setBorderPainted(false);
        transactionButton.setContentAreaFilled(false);
        transactionButton.setDefaultCapable(false);
        transactionButton.setEnabled(false);
        transactionButton.setFocusPainted(false);
        transactionButton.setFocusable(false);
        transactionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionButtonActionPerformed(evt);
            }
        });

        historyButton.setBackground(new java.awt.Color(0, 0, 51));
        historyButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        historyButton.setForeground(new java.awt.Color(242, 242, 242));
        historyButton.setText("History");
        historyButton.setBorderPainted(false);
        historyButton.setContentAreaFilled(false);
        historyButton.setDefaultCapable(false);
        historyButton.setEnabled(false);
        historyButton.setFocusPainted(false);
        historyButton.setFocusable(false);
        historyButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        logoutButton.setBackground(new java.awt.Color(0, 0, 51));
        logoutButton.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(242, 242, 242));
        logoutButton.setText("Log Out");
        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setDefaultCapable(false);
        logoutButton.setEnabled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.setFocusable(false);

        historyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assests/history.png"))); // NOI18N
        historyLogo.setText("jLabel6");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sidePanelLayout.createSequentialGroup()
                                .addComponent(historyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(historyButton))
                            .addGroup(sidePanelLayout.createSequentialGroup()
                                .addComponent(transactionLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transactionButton)
                                .addGap(27, 27, 27)))))
                .addGap(31, 31, 31))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLogo)
                    .addComponent(homeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileButton)
                    .addComponent(profileLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transactionLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(transactionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyButton)
                    .addComponent(historyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(383, 383, 383)
                .addComponent(logoutButton)
                .addGap(108, 108, 108))
        );

        movie1.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout movie1Layout = new javax.swing.GroupLayout(movie1);
        movie1.setLayout(movie1Layout);
        movie1Layout.setHorizontalGroup(
            movie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        movie1Layout.setVerticalGroup(
            movie1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        movie2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout movie2Layout = new javax.swing.GroupLayout(movie2);
        movie2.setLayout(movie2Layout);
        movie2Layout.setHorizontalGroup(
            movie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        movie2Layout.setVerticalGroup(
            movie2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        movie3.setBackground(new java.awt.Color(0, 0, 51));

        poster1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/poster1.png"))); // NOI18N

        javax.swing.GroupLayout movie3Layout = new javax.swing.GroupLayout(movie3);
        movie3.setLayout(movie3Layout);
        movie3Layout.setHorizontalGroup(
            movie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poster1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        movie3Layout.setVerticalGroup(
            movie3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(poster1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        movie4.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout movie4Layout = new javax.swing.GroupLayout(movie4);
        movie4.setLayout(movie4Layout);
        movie4Layout.setHorizontalGroup(
            movie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        movie4Layout.setVerticalGroup(
            movie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        movie5.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout movie5Layout = new javax.swing.GroupLayout(movie5);
        movie5.setLayout(movie5Layout);
        movie5Layout.setHorizontalGroup(
            movie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );
        movie5Layout.setVerticalGroup(
            movie5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        movie6.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout movie6Layout = new javax.swing.GroupLayout(movie6);
        movie6.setLayout(movie6Layout);
        movie6Layout.setHorizontalGroup(
            movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        movie6Layout.setVerticalGroup(
            movie6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        searchButton.setBackground(new java.awt.Color(0, 0, 51));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchButton.setForeground(new java.awt.Color(242, 242, 242));
        searchButton.setText("Search");

        searchlogoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/search.jpg"))); // NOI18N
        searchlogoButton.setBorderPainted(false);
        searchlogoButton.setContentAreaFilled(false);
        searchlogoButton.setDefaultCapable(false);
        searchlogoButton.setFocusPainted(false);
        searchlogoButton.setFocusable(false);
        searchlogoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchlogoButtonActionPerformed(evt);
            }
        });

        meButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assets/people.png"))); // NOI18N
        meButton.setBorderPainted(false);
        meButton.setContentAreaFilled(false);
        meButton.setDefaultCapable(false);
        meButton.setFocusPainted(false);
        meButton.setFocusable(false);

        Nowshowing.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Nowshowing.setText("Now Showing");

        upcoming.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        upcoming.setText("Coming Soon");

        scrollButton.setText("jButton11");
        scrollButton.setBorderPainted(false);
        scrollButton.setContentAreaFilled(false);
        scrollButton.setFocusPainted(false);
        scrollButton.setFocusable(false);

        scrollButton1.setText("jButton9");
        scrollButton1.setBorderPainted(false);
        scrollButton1.setContentAreaFilled(false);
        scrollButton1.setFocusPainted(false);
        scrollButton1.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upcoming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nowshowing, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(movie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movie6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(movie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(movie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scrollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(searchlogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(meButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchlogoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(meButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(searchButton))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nowshowing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(282, 282, 282)
                                .addComponent(scrollButton)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(upcoming, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movie5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(scrollButton1)
                                .addGap(89, 89, 89))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transactionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void searchlogoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchlogoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchlogoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nowshowing;
    private javax.swing.JButton historyButton;
    private javax.swing.JLabel historyLogo;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel homeLogo;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton meButton;
    private javax.swing.JPanel movie1;
    private javax.swing.JPanel movie2;
    private javax.swing.JPanel movie3;
    private javax.swing.JPanel movie4;
    private javax.swing.JPanel movie5;
    private javax.swing.JPanel movie6;
    private javax.swing.JLabel poster1;
    private javax.swing.JButton profileButton;
    private javax.swing.JLabel profileLogo;
    private javax.swing.JButton scrollButton;
    private javax.swing.JButton scrollButton1;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchlogoButton;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JButton transactionButton;
    private javax.swing.JLabel transactionLogo;
    private javax.swing.JTextField upcoming;
    // End of variables declaration//GEN-END:variables
}
