/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */
public class NewPassword extends javax.swing.JFrame {

    /**
     * Creates new form NewPassword
     */
    public NewPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        newPassword = new javax.swing.JLabel();
        reEnterPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtReEnterPassword = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assests/Logo.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 40, -1, -1));

        title.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        title.setText("Reset Password");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 122, -1, -1));

        subTitle.setFont(new java.awt.Font("Consolas", 0, 8)); // NOI18N
        subTitle.setText("Please set your new Password");
        getContentPane().add(subTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 157, -1, -1));

        newPassword.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        newPassword.setText("New Password");
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 185, -1, -1));

        reEnterPassword.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        reEnterPassword.setText("Re-enter Password");
        getContentPane().add(reEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 246, -1, -1));

        txtPassword.setText("Enter your new Password");
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 206, 252, -1));

        txtReEnterPassword.setText("Re-enter your new password");
        txtReEnterPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtReEnterPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReEnterPasswordFocusLost(evt);
            }
        });
        getContentPane().add(txtReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 267, 252, -1));

        loginButton.setBackground(new java.awt.Color(153, 153, 255));
        loginButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        loginButton.setText("Login");
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 152, -1));

        mainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Assests/FPP.jpg"))); // NOI18N
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        if (txtPassword.getText().equals("Enter your new Password")){
            txtPassword.setText("");
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        if (txtPassword.getText().isEmpty()){
            txtPassword.setText("Enter your new Password");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtReEnterPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReEnterPasswordFocusGained
        // TODO add your handling code here:
        if (txtReEnterPassword.getText().equals("Re-enter your new password")){
            txtReEnterPassword.setText("");
        }
    }//GEN-LAST:event_txtReEnterPasswordFocusGained

    private void txtReEnterPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReEnterPasswordFocusLost
        // TODO add your handling code here:
        if (txtReEnterPassword.getText().isEmpty()){
            txtReEnterPassword.setText("Re-enter your new password");
        }
    }//GEN-LAST:event_txtReEnterPasswordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel newPassword;
    private javax.swing.JLabel reEnterPassword;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtReEnterPassword;
    // End of variables declaration//GEN-END:variables
}
