/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import Controller.TheaterandHallController;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author anish
 */
public class TheatersandHall extends javax.swing.JFrame {

    /**
     * Creates new form ViewTheaters
     */
    public TheatersandHall() {
        initComponents();
//        SelectHall.setVisible(false);s
        HallAShowTime.setVisible(false);
        HallBShowTime.setVisible(false);
        HallCShowTime.setVisible(false);
        groupButtonsIntoArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CivilMall = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ChhayaCenter = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DurbarCinemax = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LabimMall = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        SelectHall = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        HallA = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        HallB = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        HallC = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        TheaterName = new javax.swing.JLabel();
        HallAShowTime = new javax.swing.JPanel();
        jLabel120 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        HallBShowTime = new javax.swing.JPanel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        HallCShowTime = new javax.swing.JPanel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        button13 = new javax.swing.JButton();
        button14 = new javax.swing.JButton();
        button15 = new javax.swing.JButton();
        button16 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button17 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel121 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(842, 702));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("📌");

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setText("Select Theaters");

        CivilMall.setBackground(new java.awt.Color(255, 255, 255));
        CivilMall.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CivilMall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CivilMallMouseClicked(evt);
            }
        });

        jLabel4.setText("Civil Mall");

        jLabel5.setText("🌟4.5");

        jLabel6.setText("QFX");

        jLabel7.setText("Kanti Marg");

        javax.swing.GroupLayout CivilMallLayout = new javax.swing.GroupLayout(CivilMall);
        CivilMall.setLayout(CivilMallLayout);
        CivilMallLayout.setHorizontalGroup(
            CivilMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CivilMallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CivilMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CivilMallLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CivilMallLayout.createSequentialGroup()
                        .addGroup(CivilMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CivilMallLayout.setVerticalGroup(
            CivilMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CivilMallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CivilMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        ChhayaCenter.setBackground(new java.awt.Color(255, 255, 255));
        ChhayaCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ChhayaCenter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChhayaCenterMouseClicked(evt);
            }
        });

        jLabel8.setText(" Chhaya Center");

        jLabel9.setText("🌟4.7");

        jLabel10.setText("QFX");

        jLabel11.setText("Amrit Marg");

        javax.swing.GroupLayout ChhayaCenterLayout = new javax.swing.GroupLayout(ChhayaCenter);
        ChhayaCenter.setLayout(ChhayaCenterLayout);
        ChhayaCenterLayout.setHorizontalGroup(
            ChhayaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChhayaCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChhayaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChhayaCenterLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ChhayaCenterLayout.createSequentialGroup()
                        .addGroup(ChhayaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ChhayaCenterLayout.setVerticalGroup(
            ChhayaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChhayaCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChhayaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        DurbarCinemax.setBackground(new java.awt.Color(255, 255, 255));
        DurbarCinemax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        DurbarCinemax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DurbarCinemaxMouseClicked(evt);
            }
        });

        jLabel12.setText("Durbar Cinemax");

        jLabel13.setText("🌟4.2");

        jLabel14.setText("QFX");

        jLabel15.setText("DurbarMarg");

        javax.swing.GroupLayout DurbarCinemaxLayout = new javax.swing.GroupLayout(DurbarCinemax);
        DurbarCinemax.setLayout(DurbarCinemaxLayout);
        DurbarCinemaxLayout.setHorizontalGroup(
            DurbarCinemaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DurbarCinemaxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DurbarCinemaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DurbarCinemaxLayout.createSequentialGroup()
                        .addGroup(DurbarCinemaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DurbarCinemaxLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        DurbarCinemaxLayout.setVerticalGroup(
            DurbarCinemaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DurbarCinemaxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DurbarCinemaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        LabimMall.setBackground(new java.awt.Color(255, 255, 255));
        LabimMall.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        LabimMall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabimMallMouseClicked(evt);
            }
        });

        jLabel16.setText("Labim Mall");

        jLabel17.setText("🌟4.6");

        jLabel18.setText("QFX");

        jLabel19.setText("Lalitpur");

        javax.swing.GroupLayout LabimMallLayout = new javax.swing.GroupLayout(LabimMall);
        LabimMall.setLayout(LabimMallLayout);
        LabimMallLayout.setHorizontalGroup(
            LabimMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabimMallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabimMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LabimMallLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LabimMallLayout.createSequentialGroup()
                        .addGroup(LabimMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LabimMallLayout.setVerticalGroup(
            LabimMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabimMallLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabimMallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CivilMall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChhayaCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DurbarCinemax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabimMall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CivilMall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChhayaCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DurbarCinemax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabimMall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Theaters & Hall Selection");
        jLabel1.setOpaque(true);

        SelectHall.setBackground(new java.awt.Color(255, 255, 255));
        SelectHall.setPreferredSize(new java.awt.Dimension(568, 242));

        jLabel20.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel20.setText("Select Hall - ");

        jLabel21.setText("👥");

        HallA.setBackground(new java.awt.Color(255, 255, 255));
        HallA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        HallA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HallAMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel22.setText("Hall A - Premium");

        jLabel23.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel23.setText("Premium");

        jLabel24.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel24.setText("Capacity : 120");

        jLabel31.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel31.setText("10:00");

        jLabel32.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel32.setText("12:30");

        jLabel33.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel33.setText("+2 more");

        javax.swing.GroupLayout HallALayout = new javax.swing.GroupLayout(HallA);
        HallA.setLayout(HallALayout);
        HallALayout.setHorizontalGroup(
            HallALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HallALayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jLabel23))
                    .addGroup(HallALayout.createSequentialGroup()
                        .addGroup(HallALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(HallALayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HallALayout.setVerticalGroup(
            HallALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallALayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HallALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        HallB.setBackground(new java.awt.Color(255, 255, 255));
        HallB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        HallB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HallBMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel25.setText("Hall C - IMAX");

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel26.setText("IMAX");

        jLabel27.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel27.setText("Capacity : 220");

        jLabel34.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel34.setText("12:00");

        jLabel35.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel35.setText("2:30");

        jLabel36.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel36.setText("+2 more");

        javax.swing.GroupLayout HallBLayout = new javax.swing.GroupLayout(HallB);
        HallB.setLayout(HallBLayout);
        HallBLayout.setHorizontalGroup(
            HallBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HallBLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(jLabel26))
                    .addGroup(HallBLayout.createSequentialGroup()
                        .addGroup(HallBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(HallBLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HallBLayout.setVerticalGroup(
            HallBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HallBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        HallC.setBackground(new java.awt.Color(255, 255, 255));
        HallC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        HallC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HallCMouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel28.setText("Hall B - Standard");

        jLabel29.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel29.setText("Standard");

        jLabel30.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel30.setText("Capacity : 180");

        jLabel37.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel37.setText("11:00");

        jLabel38.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel38.setText("1:30");

        jLabel39.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel39.setText("+2 more");

        javax.swing.GroupLayout HallCLayout = new javax.swing.GroupLayout(HallC);
        HallC.setLayout(HallCLayout);
        HallCLayout.setHorizontalGroup(
            HallCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HallCLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jLabel29))
                    .addGroup(HallCLayout.createSequentialGroup()
                        .addGroup(HallCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(HallCLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel39)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HallCLayout.setVerticalGroup(
            HallCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HallCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HallCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(HallCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        TheaterName.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        TheaterName.setText("Theater_Name");

        javax.swing.GroupLayout SelectHallLayout = new javax.swing.GroupLayout(SelectHall);
        SelectHall.setLayout(SelectHallLayout);
        SelectHallLayout.setHorizontalGroup(
            SelectHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectHallLayout.createSequentialGroup()
                .addGroup(SelectHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectHallLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel20)
                        .addGap(6, 6, 6)
                        .addComponent(TheaterName))
                    .addGroup(SelectHallLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(HallA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HallC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SelectHallLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(HallB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelectHallLayout.setVerticalGroup(
            SelectHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectHallLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(SelectHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectHallLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel21))
                    .addComponent(jLabel20)
                    .addComponent(TheaterName))
                .addGap(6, 6, 6)
                .addGroup(SelectHallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HallA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HallC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(HallB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        HallAShowTime.setBackground(new java.awt.Color(255, 255, 255));
        HallAShowTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel120.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel120.setText("Select ShowTime - Hall A - Premium");
        HallAShowTime.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 6, -1, -1));

        jLabel122.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel122.setText("🕛");
        HallAShowTime.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 27));

        button1.setText("10:00");
        button1.setBorderPainted(false);
        button1.setFocusPainted(false);
        HallAShowTime.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        button2.setText("12:30");
        button2.setBorderPainted(false);
        button2.setFocusPainted(false);
        HallAShowTime.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        button3.setText("3:00");
        button3.setBorderPainted(false);
        button3.setFocusPainted(false);
        HallAShowTime.add(button3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        button4.setText("5:30");
        button4.setBorderPainted(false);
        button4.setFocusPainted(false);
        HallAShowTime.add(button4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        button5.setText("8:00");
        button5.setBorderPainted(false);
        button5.setFocusPainted(false);
        HallAShowTime.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        button0.setText("7:30");
        button0.setBorderPainted(false);
        button0.setFocusPainted(false);
        HallAShowTime.add(button0, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel46.setText("            ");
        HallAShowTime.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, -1, 20));

        HallBShowTime.setBackground(new java.awt.Color(255, 255, 255));
        HallBShowTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel123.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel123.setText("Select ShowTime - Hall B - Standard");
        HallBShowTime.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 6, -1, -1));

        jLabel124.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel124.setText("🕛");
        HallBShowTime.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        button7.setText("10:00");
        button7.setBorderPainted(false);
        button7.setFocusPainted(false);
        HallBShowTime.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        button8.setText("12:30");
        button8.setBorderPainted(false);
        button8.setFocusPainted(false);
        HallBShowTime.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        button9.setText("3:00");
        button9.setBorderPainted(false);
        button9.setFocusPainted(false);
        HallBShowTime.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        button10.setText("5:30");
        button10.setBorderPainted(false);
        button10.setFocusPainted(false);
        HallBShowTime.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        button6.setText("7:30");
        button6.setBorderPainted(false);
        button6.setFocusPainted(false);
        HallBShowTime.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        button11.setText("8:00");
        button11.setBorderPainted(false);
        button11.setFocusPainted(false);
        HallBShowTime.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        jLabel47.setText("            ");
        HallBShowTime.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        HallCShowTime.setBackground(new java.awt.Color(255, 255, 255));
        HallCShowTime.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel125.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel125.setText("Select ShowTime - Hall C - IMAX");
        HallCShowTime.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 6, -1, -1));

        jLabel126.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel126.setText("🕛");
        HallCShowTime.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        button13.setText("10:00");
        button13.setBorderPainted(false);
        button13.setFocusPainted(false);
        HallCShowTime.add(button13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        button14.setText("12:30");
        button14.setBorderPainted(false);
        button14.setFocusPainted(false);
        HallCShowTime.add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        button15.setText("3:00");
        button15.setBorderPainted(false);
        button15.setFocusPainted(false);
        HallCShowTime.add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        button16.setText("5:30");
        button16.setBorderPainted(false);
        button16.setFocusPainted(false);
        HallCShowTime.add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        button12.setText("7:30");
        button12.setBorderPainted(false);
        button12.setFocusPainted(false);
        HallCShowTime.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        button17.setText("8:00");
        button17.setBorderPainted(false);
        button17.setFocusPainted(false);
        HallCShowTime.add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel48.setText("            ");
        HallCShowTime.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(570, 136));

        jLabel121.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel121.setText("Instructions:-");

        jLabel40.setText("📖");

        jLabel41.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel41.setText("1. First, select a theater.");

        jLabel42.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel42.setText("2. Then, choose a hall.");

        jLabel43.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel43.setText("3. Next, select a showtime.");

        jLabel44.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel44.setText("4. Click a showtime to proceed to seat selection.");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setText("Note: To change your selection, simply click a different theater or hall. And The time in Green is available Time");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel40)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel121))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel44))
                    .addComponent(jLabel45)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(jLabel121))
                .addGap(2, 2, 2)
                .addComponent(jLabel41)
                .addGap(6, 6, 6)
                .addComponent(jLabel42)
                .addGap(6, 6, 6)
                .addComponent(jLabel43)
                .addGap(6, 6, 6)
                .addComponent(jLabel44)
                .addGap(5, 5, 5)
                .addComponent(jLabel45))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectHall, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                            .addComponent(HallAShowTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HallBShowTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HallCShowTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SelectHall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HallAShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HallBShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HallCShowTime, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CivilMallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CivilMallMouseClicked
        // TODO add your handling code here:
        SelectHall.setVisible(true);
        TheaterName.setText("Civil Mall");
    }//GEN-LAST:event_CivilMallMouseClicked

    private void ChhayaCenterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChhayaCenterMouseClicked
        // TODO add your handling code here:
        SelectHall.setVisible(true);
        TheaterName.setText("Chhaya Center");
    }//GEN-LAST:event_ChhayaCenterMouseClicked

    private void DurbarCinemaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DurbarCinemaxMouseClicked
        // TODO add your handling code here:
        SelectHall.setVisible(true);
        TheaterName.setText("Durbar Cinemax");
    }//GEN-LAST:event_DurbarCinemaxMouseClicked

    private void LabimMallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabimMallMouseClicked
        // TODO add your handling code here:
        SelectHall.setVisible(true);
        TheaterName.setText("Labim Mall");
    }//GEN-LAST:event_LabimMallMouseClicked

    private void HallAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HallAMouseClicked
        // TODO add your handling code here:
        HallName = "HallA";
        HallAShowTime.setVisible(true);
        HallBShowTime.setVisible(false);
        HallCShowTime.setVisible(false);

    }//GEN-LAST:event_HallAMouseClicked

    private void HallCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HallCMouseClicked
        // TODO add your handling code here:
        HallName = "HAllB";
        HallBShowTime.setVisible(true);
        HallAShowTime.setVisible(false);
        HallCShowTime.setVisible(false);
    }//GEN-LAST:event_HallCMouseClicked

    private void HallBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HallBMouseClicked
        // TODO add your handling code here:
        HallName = "HallC";
        HallCShowTime.setVisible(true);
        HallAShowTime.setVisible(false);
        HallBShowTime.setVisible(false);
    }//GEN-LAST:event_HallBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheatersandHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheatersandHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheatersandHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheatersandHall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TheatersandHall().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChhayaCenter;
    private javax.swing.JPanel CivilMall;
    private javax.swing.JPanel DurbarCinemax;
    private javax.swing.JPanel HallA;
    private javax.swing.JPanel HallAShowTime;
    private javax.swing.JPanel HallB;
    private javax.swing.JPanel HallBShowTime;
    private javax.swing.JPanel HallC;
    private javax.swing.JPanel HallCShowTime;
    private javax.swing.JPanel LabimMall;
    private javax.swing.JPanel SelectHall;
    private javax.swing.JLabel TheaterName;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button13;
    private javax.swing.JButton button14;
    private javax.swing.JButton button15;
    private javax.swing.JButton button16;
    private javax.swing.JButton button17;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JButton[] button;

    private String HallName;
    
    private void groupButtonsIntoArray() {
        button = new javax.swing.JButton[] {
            button0, button1, button2, button3, button4, button5,
            button6, button7, button8, button9, button10, button11,
            button12, button13, button14, button15, button16, button17
        };
    }
    
    private int[] buttonTimes = {
        730, 1000, 1230, 1500, 1730, 2000,   // Hall A
        730, 1000, 1230, 1500, 1730, 2000,   // Hall B
        730, 1000, 1230, 1500, 1730, 2000    // Hall C
    };

    public void highlightBookedButton(int bookedTime) {
        for (int i = 0; i < 18; i++) {
            if (buttonTimes[i] == bookedTime) {
                button[i].setBackground(Color.GREEN);
    //            button[i].setForeground(Color.WHITE); // Optional
                button[i].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {

                    }
                });

                
            }
            else {
                button[i].setBackground(Color.ORANGE); // Reset others if needed
                button[i].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                       JOptionPane.showMessageDialog(null, "Choose Available Time Please!!");

                    }
                });
            }
        }
    }
    




}
